= Asciidoc FX - PDF CJK Patch Manual Setting Guide 
:encoding: utf-8
:lang: en
:toc: left
:numbered:
:experimental:

This guideline applies to AsciidocFX 1.7.4 / 1.6.0. (not tested in earlier versions) 

The following is translated from Chinese to English using Google Translate.

== Preface

This guide is for Windows and MacOS or other users who cannot apply automation .sh and must manually modify the settings.

The detailed steps are actually explained according to the notes in pdf-cjk-patch-XX.sh and changed to manual mode.

* XX can be replaced by TW or CN or JP or KR. 
* See XX below, please replace it with the language you want to use.	


[NOTE]
====
The installation directory of your AsciidocFX is referred to as AsciidocFX below.
If you are a Windows user, please replace the path separator from `/` to `\`.
====


== Create a font directory

`# create CJK_FONT_DIR`

Please create a directory with the following path AsciidocFX/conf/fonts/KaiGenGothic
(In Windows should be AsciidocFX\conf\fonts\KaiGenGothic) 


== Download font 

`# download CJK Fonts`

Please download the following fonts:
 
Download method, see if you are willing to use browser Firefox, Chrome or other programs.

Please find the block you want to download TW , CN , JP , KR.
Please put the downloaded fonts in the AsciidocFX/conf/fonts/KaiGenGothic directory. 

The download font URLs are organized as follows: 

[source,bash]
----
#### TW
https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicTW-Regular.ttf

https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicTW-Bold.ttf

https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicTW-Regular-Italic.ttf

https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicTW-Bold-Italic.ttf

#### CN
https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicCN-Regular.ttf

https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicCN-Bold.ttf

https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicCN-Regular-Italic.ttf

https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicCN-Bold-Italic.ttf

#### JP
https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicJP-Regular.ttf

https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicJP-Bold.ttf

https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicJP-Regular-Italic.ttf

https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicJP-Bold-Italic.ttf

#### KR
https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicKR-Regular.ttf

https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicKR-Bold.ttf

https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicKR-Regular-Italic.ttf

https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicKR-Bold-Italic.ttf

----



=== Check font correctness 

`# md5 checksum`

Please copy pdf-cjk-patch/TW/KaiGenGothicXX.fonts.md5 to the AsciidocFX/conf/fonts/KaiGenGothic directory.
You can go to the AsciidocFX/conf/fonts/KaiGenGothic directory and use the command `md5sum -c KaiGenGothicXX.fonts.md5`
Or other tools to check the consistency of downloaded fonts.

Q: What if the results of the md5sum test are inconsistent? 

* Indicates that there may be an error in downloading the font, you can try to download the font again.
* Indicates that the font may have been changed, and it is not recommended to continue.


[IMPORTANT]
.IMPORTANT
====
Because the font xml file corresponding to the fop is generated for the current https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/KaiGenGothicXX-YYYYYYY.ttf file and Modified.

If it is not a font file with the same content, the fop corresponding xml file of the following fonts cannot be applied, and it is recommended not to continue. 

====

== Copy the fop corresponding to the font xml file 

`# copy font xml`

Please copy these files in the pdf-cjk-patch/XX subdirectory below:

* KaiGenGothicXX-Regular.xml
* KaiGenGothicXX-Bold.xml
* KaiGenGothicXX-Regular-Italic.xml
* KaiGenGothicXX-Bold-Italic.xml

into the font directory AsciidocFX/conf/fonts/KaiGenGothic 

== Backup the docbook-config file 

`# backup docbook-config`

Go to the AsciidocFX/conf/docbook-config directory 

* Copy `fop.xconf.xml` , and rename to `fop.xconf.xml.org`
* Copy `fo-pdf.xsl` , and rename to  `fo-pdf.xsl.org`

== Modify the docbook-config configuration file 

`# patch docbook-config`

Copy these files from the pdf-cjk-patch/XX/ directory
 
* asciidocfx-1.7.4-pdf-cjk_fop.xconf.xml_XX.patch (for reference only)
* asciidocfx-1.7.4-pdf-cjk_fo-pdf.xsl_XX.patch (for reference only)

into the AsciidocFX/conf/docbook-config directory 

=== Modify fop.xconf.xml 

Run a text editor, Windows users are recommended to use Notepad++ 
Please enable asciidocfx-1.7.4-pdf-cjk_fop.xconf.xml_XX.patch for reference 
Please open fop.xconf.xml in the AsciidocFX/conf/docbook-config directory to prepare for editing 

.Find the following paragraph - fop.xconf.xml line 19 
[source,xml]
----
  <!-- Base URL for resolving relative URLs --> //<1>
  <base>.</base> //<2>
----
<1> line 18
<2> line 19



Refer to the content of asciidocfx-1.7.4-pdf-cjk_fop.xconf.xml_XX.patch and modify it to the following: 

[source,bash]
----
  <!-- Base URL for resolving relative URLs --> //<1>
  <base>../fonts/KaiGenGothic</base> //<2>
----
<1> line 18
<2> line 19 , Point the directory of the font file set below to our newly created fonts/KaiGenGothic directory


[IMPORTANT]
.IMPORTANT
====
Be careful not to copy // <1> // <2> etc. 
====

.find the following paragraph - fop.xconf.xml line 89 
[source,xml]
----
        <auto-detect/> // <1>
      </fonts>         // <2>
----
<1> line 89
<2> line 90

Between line 89 and line 90, please refer to asciidocfx-1.7.4-pdf-cjk_fop.xconf.xml_XX.patch (assuming TW is used) 

[source,xml]
----
         <auto-detect/> // <1>
<!-- The following are added content  --> // <2>
<font metrics-url="KaiGenGothicTW-Bold.xml" kerning="yes" embed-url="KaiGenGothicTW-Bold.ttf">  
      <font-triplet name="KaiGen Gothic TW" style="normal" weight="bold"/> 
</font>
<font metrics-url="KaiGenGothicTW-Bold-Italic.xml" kerning="yes" embed-url="KaiGenGothicTW-Bold-Italic.ttf"> 
      <font-triplet name="KaiGen Gothic TW" style="italic" weight="bold"/> 
</font>
<font metrics-url="KaiGenGothicTW-Regular.xml" kerning="yes" embed-url="KaiGenGothicTW-Regular.ttf"> 
      <font-triplet name="KaiGen Gothic TW" style="normal" weight="normal"/> 
</font>
<font metrics-url="KaiGenGothicTW-Regular-Italic.xml" kerning="yes" embed-url="KaiGenGothicTW-Regular-Italic.ttf"> 
      <font-triplet name="KaiGen Gothic TW" style="italic" weight="normal"/> 
</font>
<!-- The above is added content  --> // <3>
       </fonts>
----
<1> line 89
<2> start content 
<3> end content 

Please replace the TW in it with CN, JP, KR by yourself.

=== Modify fo-pdf.xsl 

Run a text editor, Windows users are recommended to use Notepad++.


Please enable asciidocfx-1.7.4-pdf-cjk_fo-pdf.xsl_XX.patch for reference.
Please open fo-pdf.xsl in the AsciidocFX/conf/docbook-config directory to prepare for editing.

.find the following paragraphs - fo-pdf.xsl line 30, 35, 62, 66, 70.
[source,xml]
----
<xsl:attribute name="font-family">Sans-serif,Arial</xsl:attribute> // <1>
<xsl:attribute name="font-family">Sans-serif,Arial</xsl:attribute> // <2>
<xsl:text>Sans-serif,Arial,Arial Unicode MS,Helvetica,serif,Georgia,Times New Roman</xsl:text> // <3>
<xsl:text>Sans-serif,Arial,Arial Unicode MS,Helvetica,serif,Georgia,Times New Roman</xsl:text> // <4>
<xsl:text>Liberation Mono,Lucida Console,Monaco,Consolas,Courier New,Courier,monospace,Arial Unicode MS,Lucida Sans Unicode</xsl:text> // <5>
----
<1> line 30
<2> line 35
<3> line 62
<4> line 66
<5> line 70

Please refer to asciidocfx-1.7.4-pdf-cjk_fo-pdf.xsl_XX.patch and add the corresponding font name `KaiGen Gothic XX`
For Example: `KaiGen Gothic TW` 

The modified content is as follows: Assuming that TW is used 

[source,bash]
----
<xsl:attribute name="font-family">Sans-serif,Arial,KaiGen Gothic TW</xsl:attribute> // <1>
<xsl:attribute name="font-family">Sans-serif,Arial,KaiGen Gothic TW</xsl:attribute> // <2>
<xsl:text>Sans-serif,Arial,Arial Unicode MS,KaiGen Gothic TW,Helvetica,serif,Georgia,Times New Roman</xsl:text> // <3>
<xsl:text>Sans-serif,Arial,Arial Unicode MS,KaiGen Gothic TW,Helvetica,serif,Georgia,Times New Roman</xsl:text> // <4>
<xsl:text>Liberation Mono,Lucida Console,Monaco,Consolas,Courier New,Courier,monospace,Arial Unicode MS,KaiGen Gothic TW,Lucida Sans Unicode</xsl:text> // <5>
----
<1> line 30
<2> line 35
<3> line 62
<4> line 66
<5> line 70



[IMPORTANT]
.IMPORTANT
====
`<xsl:text>FontName,FontName, ...</xsl:text>` may vary between versions. 

Do not directly overwrite the original settings, please add `KaiGen Gothic TW` manually. Remember to add commas ‵,` to separate from other font names.
====


== Complete AsciidoxFX PDF CJK Patch

=== Testing 
`# Open Example Asciidoc to test`

Under the pdf-cjk-patch/testdoc directory, ready-made test files are provided 

* Execute AsciidocFX and open the AsciidocFX/pdf-cjk-patch/testdoc directory 
* Open PDF-CJK-TEST_XX.adoc 
* Then click PDF -> Save in the upper right corner 
* After that, it can be found in the AsciidocFX/pdf-cjk-patch/testdoc directory 
* See the PDF produced by the action just now (PDF-CJK-TEST_XX.pdf) 

== Delete patch file

`# delete patch file`

Please go to this path AsciidocFX/conf/docbook-config/ and delete these two files:

* asciidocfx-1.7.4-pdf-cjk_fop.xconf.xml_XX.patch
* asciidocfx-1.7.4-pdf-cjk_fo-pdf.xsl_XX.patch

== Delete md5

`# delete md5`

Please delete AsciidocFX/conf/fonts/KaiGen Gothic/KaiGenGothicXX.font.md5.

== Summary

So far, the relevant steps to manually modify the settings are the same as the steps in pdf-cjk-patch-XX.sh, just through manual work. 


=== Windows users

Windows users can create the bat file on windows by themselves according to this step. to complete automation.

A few important commands would be:

* Download file command: `wget` on Linux, you need find another command on Windows.
* Check md5 checksum command: use `md5sum` on Linux, find it yourself on Windows.
* patch file command : use `patch` on Linux, find it yourself on Windows.
