= AsciidocFXPDFCJKテスト
life888888
:doctype: article
:encoding: utf-8
:lang: en
:toc: left
:numbered:
:experimental: 

これは、AsciidocFXがPDFをエクスポートするときに、日本語のフォント設定が完全​​で正しいかどうかをテストするためのテストファイルです。

生成されたPDFにこのメッセージが表示されている場合は、AsciidocFXフォント設定が完了していることを意味します。

これはGoogle翻訳によって生成されたコンテンツです。 

== フォントスタイルテスト

一般的なフォントスタイル： 祇園精舎（ぎをんしやうじや）の鐘（かね）の声、諸行無常（しよぎやうむじやう）の響（ひび）きあり。

大胆なフォントスタイル： **娑羅双樹（しやらさうじゆ）の花の色、盛者必衰（じやうしやひつすい）の理（ことわり）をあらはす。**

イタリックフォントスタイル： __おごれる人も久（ひさ）しからず、ただ春の夜（よ）の夢（ゆめ）のごとし。__

イタリックの太字フォントスタイル： __**たけき者もつひには滅（ほろ）びぬ、ひとへに風の前の塵（ちり）に同じ。**__

[underline]#下線#、これは^上付き文字^、これは~下付き文字~です 

=== Tier3タイトルテスト 

一般的なフォントスタイル： 祇園精舎（ぎをんしやうじや）の鐘（かね）の声、諸行無常（しよぎやうむじやう）の響（ひび）きあり。

大胆なフォントスタイル： **娑羅双樹（しやらさうじゆ）の花の色、盛者必衰（じやうしやひつすい）の理（ことわり）をあらはす。**

イタリックフォントスタイル： __おごれる人も久（ひさ）しからず、ただ春の夜（よ）の夢（ゆめ）のごとし。__

イタリックの太字フォントスタイル： __**たけき者もつひには滅（ほろ）びぬ、ひとへに風の前の塵（ちり）に同じ。**__

==== Tier4タイトルテスト 

一般的なフォントスタイル： 祇園精舎（ぎをんしやうじや）の鐘（かね）の声、諸行無常（しよぎやうむじやう）の響（ひび）きあり。

大胆なフォントスタイル： **娑羅双樹（しやらさうじゆ）の花の色、盛者必衰（じやうしやひつすい）の理（ことわり）をあらはす。**

イタリックフォントスタイル： __おごれる人も久（ひさ）しからず、ただ春の夜（よ）の夢（ゆめ）のごとし。__

イタリックの太字フォントスタイル： __**たけき者もつひには滅（ほろ）びぬ、ひとへに風の前の塵（ちり）に同じ。**__

== チェック項目

.Checked list
- [ ] 日本語フォントを表示するかどうか
- [ ] 一般的なフォントが正常に表示されるかどうか
- [ ] 太字フォントが正常に表示されるかどうか
- [ ] イタリックフォントが正常に表示されるかどうか
- [ ] イタリックの太字フォントは正常に表示されますか？ 

